apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadvisor
  labels:
    app: cadvisor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      containers:
        - name: cadvisor
          image: gcr.io/cadvisor/cadvisor:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8070
          volumeMounts:
            - mountPath: /rootfs
              name: root
            - mountPath: /var/run
              name: var-run
            - mountPath: /sys
              name: sys-host-dir
      volumes:
        - name: root
          hostPath:
            path: /
            type: Directory
        - name: var-run
          hostPath:
            path : /var/run
            type: Directory
        - name: sys-host-dir
          hostPath:
            path: /sys
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: cadvisor-service
spec:
  type: LoadBalancer
  externalIPs:
    - 192.168.49.2
  ports:
    - port: 80
      targetPort: 8070
      protocol: TCP
      nodePort: 33000
  selector:
    app: cadvisor
