apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
    distributor:
      receivers:
        zipkin:        
    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-traces
  labels:
    app: tempo-traces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo-traces
  template:
    metadata:
      labels:
        app: tempo-traces
    spec:
      containers:
        - name: tempo-traces
          image: grafana/tempo
          imagePullPolicy: Always
          ports:
            - containerPort: 3200
            - containerPort: 9411
          args:
            - "-config.file=/etc/tempo/tempo.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/tempo
      volumes:
        - name: config
          configMap:
            name: tempo-config

---
apiVersion: v1
kind: Service
metadata:
  name: tempo-service
spec:
  ports:
    - name: tempo
      targetPort: 3200
      port: 81
    - name: zipkin
      targetPort: 9411
      port: 82
  selector:
    app: tempo-traces
