apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-traces
  labels:
    app: tempo-traces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo-traces
  template:
    metadata:
      labels:
        app: tempo-traces
    spec:
      containers:
        - name: tempo-traces
          image: grafana/tempo
          imagePullPolicy: Always
          ports:
            - containerPort: 3200
            - containerPort: 9411
          command: [ "-config.file=/etc/tempo.yaml" ]
          volumeMounts:
            - mountPath: /etc/tempo.yml
              name: tempo-config
            - mountPath: /tmp/tempo
              name: tempo-data
      volumes:
        - name: tempo-config
          hostPath:
            path: /var/jenkins_home/workspace/k8s_microservice/docker/tempo.yml
        - name: tempo-data
          hostPath:
            path: /var/jenkins_home/workspace/k8s_microservice/docker/tempo-data

---
apiVersion: v1
kind: Service
metadata:
  name: tempo-service
spec:
  ports:
    - name: tempo
      targetPort: 8081
      port: 8081
    - name: zipkin
      targetPort: 9411
      port: 9411
  selector:
    app: tempo-traces
