spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
      reload:
        enabled: true

ribbon:
  kubernetes:
    enabled: true


logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.openfeign: DEBUG