global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'customer-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['customer-service:8081']
        labels:
          application: 'My Customer App Service Application'

  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['inventory-service:8082']
        labels:
          application: 'My Inventory Service Application'

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['order-service:8083']
        labels:
          application: 'My Order Service Application'

