apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-service-app
  labels:
    app: cloud-config-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config-service-app
  template:
    metadata:
      labels:
        app: cloud-config-service-app
    spec:
      containers:
        - name: cloud-config-service-app
          image: aminesaber/config-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config-service-svc
spec:
  ports:
    - targetPort: 8888
      port: 80
  selector:
    app: cloud-config-service-app
