apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
  labels:
    app: order-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : order-service-app
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      initContainers:
        - name: wait-for-services
          image: appropriate/curl
          command: ['sh', '-c', 'until curl -sS customer-service-svc:80/actuator/health; do echo "Waiting for customer service"; sleep 5; done']
        - name: wait-for-inventory
          image: appropriate/curl
          command: ['sh', '-c', 'until curl -sS inventory-service-svc:80/actuator/health; do echo "Waiting for inventory service"; sleep 5; done']
      containers:
      - name: order-service-app
        image: aminesaber/order-service:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8083

---

kind: Service
apiVersion: v1
metadata:
  name:  order-service-svc
spec:
  selector:
    app:  order-service-app
  ports:
  - port:  80
    targetPort:  8083
