apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    app: consul
spec:
  clusterIP: None
  ports:
    - port: 8500
      name: consul
  selector:
    app: consul

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
spec:
  serviceName: "consul"
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: consul:1.15.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8500
          readinessProbe:
            httpGet:
              path: /v1/status/leader
              port: 8500
            initialDelaySeconds: 10
            periodSeconds: 5
#          env
  :
#            - name: CONSUL_BIND_INTERFACE
#              value: eth0
#          command: ["consul", "agent", "-server", "-bootstrap-expect=1", "-ui", "-client=0.0.0.0", "-bind=0.0.0.0"]
#          volumeMounts:
#            - name: consul-data
#              mountPath: /consul/data
#  volumeClaimTemplates:
#    - metadata:
#        name: consul-data
#      spec:
#        accessModes: ["ReadWriteOnce"]
#        resources:
#          requests:
#            storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: consul-lb
  labels:
    app: consul
spec:
  selector:
    app: consul
  type: NodePort
  ports:
    - port: 80
      targetPort: 8500