apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-cm
data:
  spring.config.import: "optional:consul:localhost:8500,vault://"

---

apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    app: consul
spec:
  clusterIP: None
  ports:
    - port: 8084
      name: consul
  selector:
    app: consul

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
spec:
  serviceName: "consul"
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: aminesaber/consul-vault-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: consul_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: consul-cm
                  key: consul_service_address

---

apiVersion: v1
kind: Service
metadata:
  name: consul-lb
  labels:
    app: consul
spec:
  selector:
    app: consul
  type: NodePort
  ports:
    - port: 80
      targetPort: 8084