apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
spec:
  serviceName: "consul"
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: consul:1.11.4
          imagePullPolicy: Always
          ports:
            - containerPort: 8500
          env:
            - name: CONSUL_BIND_INTERFACE
              value: eth0
          command: ["/bin/sh", "-c", "consul agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -bind=0.0.0.0"]
          volumeMounts:
            - name: consul-data
              mountPath: /consul/data
  volumeClaimTemplates:
    - metadata:
        name: consul-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi