apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  KC_DB_URL: "jdbc:postgresql://postgres-db:5432/keycloak"
  KC_DB_USERNAME: "dbuser"
  KC_HOSTNAME: "keycloak"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HTTP_ENABLED: "true"
  KC_PROXY: "edge"
  KEYCLOAK_ADMIN: "saber"

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
stringData:
  KC_DB_PASSWORD: "saber"
  KEYCLOAK_ADMIN_PASSWORD: "saber"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest
          args: ["start-dev"]
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: keycloak-config
            - secretRef:
                name: keycloak-secret
          env:
            - name: KC_DB
              value: postgres
            - name: KEYCLOAK_HOSTNAME
              value: keycloak
            - name: KEYCLOAK_HTTP_PORT
              value: "8095"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: LoadBalancer
  externalIPs:
    - 192.168.49.2
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8080
      nodePort: 31095